feat: hamburguer menu
LadybirdBrowser/ladybird.org pull request #65
Opened 2024-07-31 12:34 UTC by Cauatn

![image](https://github.com/user-attachments/assets/cc7d3db0-d038-4ae2-bcc8-3f078d22f931)

![image](https://github.com/user-attachments/assets/8a927d1f-b1fb-4bd1-b5fd-81e82db91736)

Closes (#6 )

2024-08-01 07:54 UTC, AtkinsSJ commented
"Hamburger" is still misspelled.

2024-08-13 08:52 UTC, Mafrans commented
Perhaps a nitpick, but the icon could be slightly smaller, 36x36 is very large for an icon. My suggestion would be to reduce its size to 24x24 and place it in a 36x36 or 48x48 rounded box (perhaps with a hover effect?) which acts as its new bounding area.
![image](https://github.com/user-attachments/assets/64481fb6-3f3f-4c39-86de-d90b46f65fdd)

2024-08-18 12:40 UTC, Cauatn commented
> Perhaps a nitpick, but the icon could be slightly smaller, 36x36 is very large for an icon. 

@Mafrans It's a nice change, but some discutions on the discord suggests that the project know is passing into a redesign by some company that they hired. Gonna re-size the icon anymay but it's hard to tell if the change is gonna pass.

2024-08-19 14:12 UTC, ADKaster commented
@Cauatn you've misunderstood the conversations. The design artifacts already exist, as the company was hired prior to the launch of the non-profit

2024-08-19 14:44 UTC, Cauatn commented
Oh, ok! Sorry for giving the wrong information then

2025-03-07 05:08 UTC, Bashamega requested changes

2025-03-07 05:08 UTC, Bashamega commented on src/components/global/hamburger.astro
Maybe give it a better background color, also a slide-in, slide-out animation to make it smooth.

2026-06-05 07:17 UTC, gmta commented
Thank you for taking the time to work on this pull request.

As announced in ["Changing How We Develop Ladybird"](https://ladybird.org/posts/changing-how-we-develop-ladybird/), we are closing all currently open public pull requests as part of ending the public code contribution path for Ladybird.

This is not a judgment on the quality of your work; we are very grateful for the effort you put into this pull request. But as of right now, code changes to the Ladybird codebase will only be introduced by project maintainers.

We still welcome clear bug reports, reduced test cases, website testing, standards discussion, design discussion, security reports, and technical feedback.

2026-06-05 07:17 UTC, closed without merging